services:
  db:
    image: postgres:16-alpine
    container_name: markify-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-markify_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-markify123}
      POSTGRES_DB: ${POSTGRES_DB:-markify}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-markify_user} -d $${POSTGRES_DB:-markify}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://${POSTGRES_USER:-markify_user}:${POSTGRES_PASSWORD:-markify123}@db:5432/${POSTGRES_DB:-markify}?schema=public
    container_name: markify-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-markify_user}:${POSTGRES_PASSWORD:-markify123}@db:5432/${POSTGRES_DB:-markify}?schema=public
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      AUTH_TRUST_HOST: "true"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: markify-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@markify.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
